version: '3.8'
services:
  prefect:
    image: prefecthq/prefect:2
    container_name: prefect-server
    command: prefect server start --host 0.0.0.0
    ports:
      - "4200:4200"
      - "8080:8080"
    volumes:
      - ./prefect_data:/root/.prefect
    restart: unless-stopped
