http:
  routers:
    openclaw:
      rule: "Host(`openclaw.home`)"
      entryPoints:
        - web
      service: openclaw
    goblinclaw:
      rule: "Host(`goblinclaw.home`)"
      entryPoints:
        - web
      service: goblinclaw

  services:
    openclaw:
      loadBalancer:
        servers:
          - url: "http://ford.local:18789"
    goblinclaw:
      loadBalancer:
        servers:
          - url: "http://ford.local:18889"
